
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["Students/Students.csproj", "Students/"]
RUN dotnet restore "Students/Students.csproj"
COPY . .
WORKDIR "/src/Students"
RUN dotnet build "Students.csproj" -c Release -o /app/build
RUN dotnet publish "Students.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Students.dll"]
